### ISSUE TITLE
Support for future kernel versions

### ISSUE THREAD

**Issue by zkorpio1** [corneal64/Realtek-USB-Wireless-Adapter-Drivers#1]
Hi, thanks so much for this great solution, i would like to know what do we need to do to have support and get working this driver for future kernel versions.

Today i tried with 5.3.0-050300-generic in ubuntu disco and i got that this kernel is not supported.

Thanks in advance

**Comment by corneal64** [comment]
I have just updated the git repository and added support for kernel 4.15.x ~ 5.3.x, try it out and let me know if it works. Thanks.
