### ISSUE TITLE
Driver Build is failing

### ISSUE THREAD

**Issue by sumanalla** [corneal64/Realtek-USB-Wireless-Adapter-Drivers#12]
Driver Build is failing with the below errors, any help?

XXXX@XXXX~/Documents/Realtek-USB-Wireless-Adapter-Drivers$ sudo dkms build rtl8188fu/1.0

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
'make' all KVER=5.4.0-1022-raspi...(bad exit status: 2)
ERROR (dkms apport): binary package for rtl8188fu: 1.0 not found
Error! Bad return status for module build on kernel: 5.4.0-1022-raspi (armv7l)
Consult /var/lib/dkms/rtl8188fu/1.0/build/make.log for more information.

XXXX@XXXX:~/Documents/Realtek-USB-Wireless-Adapter-Drivers$ cat /var/lib/dkms/rtl8188fu/1.0/build/make.log
DKMS make.log for rtl8188fu-1.0 for kernel 5.4.0-1022-raspi (armv7l)
Thursday 19 November 2020 01:16:35 AM IST
make ARCH=armv7l CROSS_COMPILE= -C /lib/modules/5.4.0-1022-raspi/build M=/var/lib/dkms/rtl8188fu/1.0/build  modules
make[1]: Entering directory '/usr/src/linux-headers-5.4.0-1022-raspi'
Makefile:698: arch/armv7l/Makefile: No such file or directory
make[1]: *** No rule to make target 'arch/armv7l/Makefile'.  Stop.
make[1]: Leaving directory '/usr/src/linux-headers-5.4.0-1022-raspi'
make: *** [Makefile:470: modules] Error 2

**Comment by corneal64** [comment]
Did you try the ARM build?
