### ISSUE TITLE
RealteK 502.11N RTL8188etv USB Network Adapter 

### ISSUE THREAD

**Issue by jacqpret** [corneal64/Realtek-USB-Wireless-Adapter-Drivers#2]
Good Afternoon

Does your driver support monitor mode & frame injection.
Thank You
Jacques

**Comment by corneal64** [comment]
Hey there,

It did not work for me, but that's because my device does not support it.
You can take a look at this. It might help. 
[Getting-RTL8188-to-work-with-Kali-in-monitor-mode](https://forums.kali.org/showthread.php?37911-Getting-RTL8188-to-work-with-Kali-in-monitor-mode)

**Comment by jacqpret** [comment]
Thank you will give it a go
