### ISSUE TITLE
Please, add monitor mode.

### ISSUE THREAD

**Issue by ghost** [corneal64/Realtek-USB-Wireless-Adapter-Drivers#3]
after: "sudo airmon-ng start wlx00e0202ccd43"

phy1	wlx00e0202ccd43	rtl8188fu	Realtek Semiconductor Corp. 
Interface 15mon is too long for linux so it will be renamed to the old style (wlan#) name.

 ERROR adding monitor mode interface: command failed: Operation not supported (-95)
		(mac80211 station mode vif disabled for [phy1]wlx00e0202ccd43)

**Comment by corneal64** [comment]
Please uninstall the drivers and reinstall them after making the following changes to the "Makefile":
_disable power saving and enable monitor mode._

_Please edit Makefile and search for the following options and change them as stated below:_

**$ ./rtl8188fu/Makefile:
CONFIG_POWER_SAVING = n
CONFIG_WIFI_MONITOR = y**

Then recompile and install the drivers.

-----

git clone https://github.com/corneal64/Realtek-USB-Wireless-Adapter-Drivers.git
cd Realtek-USB-Wireless-Adapter-Drivers

**EDIT "Makefile" AND MAKE CHANGES**

sudo dkms add ./rtl8188fu
sudo dkms build rtl8188fu/1.0
sudo dkms install rtl8188fu/1.0
sudo cp ./rtl8188fu/firmware/rtl8188fufw.bin /lib/firmware/rtlwifi/

-----

Please let me know if it works, then I can make these changes permanent. Thank you.

**Comment by ghost** [comment]
i did it but still dont work, idk what to do.

Em ter, 25 de fev de 2020 07:50, Cornelius Edward <notifications@github.com>
escreveu:

**Comment by ghost** [comment]
when i run "iw list" it shows monitor mode as available.

Em dom, 1 de mar de 2020 15:18, Juan Silva <filofreus@gmail.com> escreveu:

**Comment by corneal64** [comment]
My adapter does not support monitor mode, maybe it's because it's a cheap adapter. I don't know if there are other solutions out there. Let me know if you find any.

**Comment by duttasukanta** [comment]
You can still use monitor mode!!!!!!!
Try this:
$ sudo iwconfig wlan0 mode monitor
$ sudo airodump-ng wlan0
It will list all available networks in details with BSSID
