### ISSUE TITLE
ARM build support

### ISSUE THREAD

**Issue by virgesmith** [corneal64/Realtek-USB-Wireless-Adapter-Drivers#5]
This doesn't work out-of-the-box for ARM arch. On a raspberrry pi zero (armv6l) I had to change line 404 of [Makefile](https://github.com/corneal64/Realtek-USB-Wireless-Adapter-Drivers/blob/master/rtl8188fu/Makefile) from

`SUBARCH := $(shell uname -m | sed -e s/i.86/i386/)`

to 

`SUBARCH := $(shell uname -m | sed -e s/i.86/i386/ | sed -e s/armv6l/arm/)`

FWIW I didn't submit a PR as this change isn't general enough and I've only tested on one hardware platform.

Hope this helps

**Comment by corneal64** [comment]
Sure, thanks. I'll add a link to this issue.

**Comment by janat08** [comment]
Can a example patchfile for this be written?

**Comment by ulidtko** [comment]
@janat08 such a patch is really simple to make if you know basic git:
```diff
diff --git i/rtl8188fu/Makefile w/rtl8188fu/Makefile
index 5300bf2..9ece77e 100644
--- i/rtl8188fu/Makefile
+++ w/rtl8188fu/Makefile
@@ -401,7 +401,7 @@ EXTRA_CFLAGS += -DDM_ODM_SUPPORT_TYPE=0x04
 ifeq ($(CONFIG_PLATFORM_I386_PC), y)
 EXTRA_CFLAGS += -DCONFIG_LITTLE_ENDIAN
 EXTRA_CFLAGS += -DCONFIG_IOCTL_CFG80211 -DRTW_USE_CFG80211_STA_EVENT
-SUBARCH := $(shell uname -m | sed -e s/i.86/i386/)
+SUBARCH := $(shell uname -m | sed -e s/i.86/i386/ | sed -e s/armv6l/arm/)
 ARCH ?= $(SUBARCH)
 CROSS_COMPILE ?=
 KVER  := $(shell uname -r)
```

**Comment by janat08** [comment]
ty, I use GUI so don't know this formatting to recognize that this is just a local commit.

**Comment by janat08** [comment]
Useful commands for other people, updpkgsums, and also change sources field which lists other patches in pkgbuild.

It doesn't work. Firstly the above example is missing commit code (its abbreviated with ...). Second I get this:
```
(1/1) Remove DKMS modules
:: Processing package changes...
Error! There are no instances of module: 8188fu
r8.1d12cae located in the DKMS tree.
error: command failed to execute correctly
(1/1) reinstalling 8188fu-dkms                     [####] 100%
Error! Could not find module source directory.
Directory: /usr/src/8188fu-r8.1d12cae does not exist.
```

**Comment by janat08** [comment]
Cant you publish a fork instead?

**Comment by corneal64** [comment]
Hey, let me know if it works on your ARM device then I can make changes to the Makefile.

**Comment by janat08** [comment]
I'm failing at installing it altogether.

**Comment by corneal64** [comment]
Oh I see... what exactly is going wrong?

**Comment by janat08** [comment]
Says in the post above. I use the overwrite flag, or something like that
(it says previous install was detected).

**Comment by corneal64** [comment]
Well first remove the partially installed version.

run `dkms status` to see if it's added to dkms.
then remove using ` sudo dkms remove rtl8188fu/1.0 --all `

After that, download the repo again and change the Makefile

Replace this line:

SUBARCH := $(shell uname -m | sed -e s/i.86/i386/)

With this line: 

SUBARCH := $(shell uname -m | sed -e s/i.86/i386/ | sed -e s/armv6l/arm/)

Then build and see if it works!

**Comment by janat08** [comment]
I'm told building drivers is a bad idea. Can I get a link for what I'm suppose to do, if using aur patches isn't an option.

**Comment by janat08** [comment]
Once again you could probably just publish a separate package for arm.

**Comment by janat08** [comment]
sudo dkms remove rtl8188fu/1.0 --all
returned that nothing was found.

**Comment by corneal64** [comment]
Then I think you haven't installed the drivers previously. 
Also do you have dkms installed properly? Sometimes dkms causes issues. 

I don't think building drivers is bad. Most coders like to build their drivers, cause they like to take a look at the source code and don't just trust some pre-built binary.

**Comment by janat08** [comment]
So I did make ARCH=aarch64, what's next? DKMS is installed.

**Comment by janat08** [comment]
So I just reuploaded the package https://aur.archlinux.org/packages/8188fu-dkms-arm . It tries to install it with different version though: 
Installing 8188fu-dkms-arm (r9.4d9d884-1)...
Configuring 8188fu-dkms-arm...
Error! Could not find module source directory.
Error while configuring 
Directory: /usr/src/8188fu-r9.4d9d884 does not exist.
Error: command failed to execute correctly
Running post-transaction hooks...
Arming ConditionNeedsUpdate...
Install DKMS modules
==> dkms install 8188fu/pkgver -k 4.19.122-1-MANJARO-ARM
Error! Bad return status for module build on kernel: 4.19.122-1-MANJARO-ARM (aarch64)
Error while configuring 
Consult /var/lib/dkms/8188fu/pkgver/build/make.log for more information.
==> Warning, `dkms install 8188fu/pkgver -k 4.19.122-1-MANJARO-ARM' returned 10
Transaction successfully finished.

**Comment by corneal64** [comment]
Since you're using arch take a look at [this](https://aur.archlinux.org/cgit/aur.git/tree/?h=8188eu-dkms)

**Comment by janat08** [comment]
I'm using manjaro, and still saw my package in the AUR, should I upload it elsewhere?

**Comment by janat08** [comment]
Did you provide that as an example for package making or something to install?

**Comment by corneal64** [comment]
To install! A user said that the 8188eu drivers also work on 8188fu. So you can try and see if it works for you. 

Also [this](https://aur.archlinux.org/packages/8188fu-dkms) driver should work. I have used it on my machine running Manjaro.

**Comment by janat08** [comment]
The eu version didn't work.
Building module:
cleaning build area....
CONFIG_RTL8188EU=m make -C /usr/lib/modules/4.19.122-1-MANJARO-ARM/build M=/var/lib/dkms/8188eu/v4.3.0.8_13968/build modules.................(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.19.122-1-MANJARO-ARM (aarch64)
Error while configuring 
Consult /var/lib/dkms/8188eu/v4.3.0.8_13968/build/make.log for more information.
Error: command failed to execute correctly
Running post-transaction hooks...
Arming ConditionNeedsUpdate...
Install DKMS modules
==> dkms install 8188eu/v4.3.0.8_13968 -k 4.19.122-1-MANJARO-ARM
Error! Bad return status for module build on kernel: 4.19.122-1-MANJARO-ARM (aarch64)
Error while configuring 
Consult /var/lib/dkms/8188eu/v4.3.0.8_13968/build/make.log for more information.
==> Warning, `dkms install 8188eu/v4.3.0.8_13968 -k 4.19.122-1-MANJARO-ARM' returned 10
Transaction successfully finished.

**Comment by janat08** [comment]
I reinstalled dkms, and the EU version won't find headers:
DKMS: add completed.
Error! echo
Error while configuring 
Your kernel headers for kernel 4.19.122-1-MANJARO-ARM cannot be found at

While the fu version still gets the same error:
Configuring 8188fu-dkms...
Error! Could not find module source directory.
Error while configuring 
Directory: /usr/src/8188fu-r8.1d12cae does not exist.
Error: command failed to execute correctly
