### ISSUE TITLE
LV-UW06 Wireless USB Adapter not detecting in Ubuntu 20.04 LTS in Desktop

### ISSUE THREAD

**Issue by maheshordex** [corneal64/Realtek-USB-Wireless-Adapter-Drivers#6]
I want to use Wireless USB Adapter for connect wifi in my desktop.

I have attached photo of Wireless USB Adapter and my ubuntu os information.

Can't find wifi drivers for 0bda:f179 Realtek Semiconductor Corp

I tried with your suggestion but not working really need help 

drivers are not working for me somehow it shows icon off wifi but when i am click on Select network nothing is visible.

--------------------------------------------------------------------------------------------------------

lsusb result

hp@HP-Computer:~$ lsusb
Bus 002 Device 004: ID 18d1:4ee2 Google Inc. Nexus Device (debug)
Bus 002 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 005: ID 0bda:f179 Realtek Semiconductor Corp.
Bus 001 Device 004: ID 046d:c31d Logitech, Inc. Media Keyboard K200
Bus 001 Device 003: ID 046d:c077 Logitech, Inc. M105 Optical Mouse
Bus 001 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

--------------------------------------------------------------------------------------------------------------

iwconfig result
hp@HP-Computer:~$ iwconfig
eno1 no wireless extensions.

lo no wireless extensions.

wlx00e0222cf986 unassociated Nickname:"<WIFI@REALTEK>"
Mode:Managed Frequency=2.412 GHz Access Point: Not-Associated
Sensitivity:0/0
Retry:off RTS thr:off Fragment thr:off
Power Management:off
Link Quality=0/100 Signal level=0 dBm Noise level=0 dBm
Rx invalid nwid:0 Rx invalid crypt:0 Rx invalid frag:0
Tx excessive retries:0 Invalid misc:0 Missed beacon:0

--------------------------------------------------------

    hp@HP-Computer:~$ sudo lshw -class network
    [sudo] password for hp: 
      *-network                 
           description: Ethernet interface
           product: 82579LM Gigabit Network Connection (Lewisville)
           vendor: Intel Corporation
           physical id: 19
           bus info: pci@0000:00:19.0
           logical name: eno1
           version: 04
           serial: 08:2e:5f:11:1f:48
           size: 100Mbit/s
           capacity: 1Gbit/s
           width: 32 bits
           clock: 33MHz
           capabilities: pm msi bus_master cap_list ethernet physical tp 10bt 10bt-fd 100bt 100bt-fd 1000bt-fd autonegotiation
           configuration: autonegotiation=on broadcast=yes driver=e1000e driverversion=3.2.6-k duplex=full firmware=0.13-4 ip=192.168.0.103 latency=0 link=yes multicast=yes port=twisted pair speed=100Mbit/s
           resources: irq:28 memory:fe400000-fe41ffff memory:fe428000-fe428fff ioport:f080(size=32)
      *-network
           description: Wireless interface
           physical id: 2
           bus info: usb@1:1.5
           logical name: wlx00e0222cf986
           serial: 00:e0:22:2c:f9:86
           capabilities: ethernet physical wireless
           configuration: broadcast=yes driver=rtl8188fu multicast=yes wireless=unassociated

[![enter image description here][1]][1]

[![enter image description here][2]][2]

[![enter image description here][3]][3]

[![enter image description here][4]][4]

  [1]: https://i.stack.imgur.com/o8srA.jpg
  [2]: https://i.stack.imgur.com/Dvn5J.jpg
  [3]: https://i.stack.imgur.com/mon3e.png
  [4]: https://i.stack.imgur.com/o8PJg.png

**Comment by corneal64** [comment]
I think it's due to the kernel that you're using.
This driver only supports **kernel 4.15.x ~ 5.3.x**

run `uname -r` to see which kernel you're using.

**Comment by maheshordex** [comment]
@corneal64 
i have this kernel
5.4.0-31-generic

**Comment by maheshordex** [comment]
@corneal64 
is there any way we can downgrade ther kernel version 

Or

Any new driver which will work for 5.4.0-31-generic ?

I am finding this from last 1 month really need this.

**Comment by corneal64** [comment]
Take a look at [this post](https://itsfoss.com/upgrade-linux-kernel-ubuntu/)

**Comment by corneal64** [comment]
Kernel 5.6 support added!

**Comment by maheshordex** [comment]
@corneal64 
It is really nice to have 5.6 support.
But unfortunately not working for me same issue i mentioned. :(

**Comment by corneal64** [comment]
That's strange. I've tested it with a 5.6 kernel and it worked fine.

**Comment by maheshordex** [comment]
Yes, it's strange for me also.

Do you the issue coming related to secure boot ?

Because i read some where if nothing will work than i need to turn off secure boot.

But i didn't find option in BIOS for UEFI secure boot.

**Comment by corneal64** [comment]
I'm not sure about that.

If you can't find any options about secure boot, in BIOS, then maybe you're not using it.
Or try to look for "Legacy boot."

In some computers if you turn on "Legacy boot" then "secure boot" is turned off.
But that also depends on the computer manufacturer.

**Comment by maheshordex** [comment]
Thank you so much for your help :)

**Comment by corneal64** [comment]
No problem :)

**Comment by maheshordex** [comment]
@corneal64 I formatted system and install Linux mint it is working now in first try.
Thankssssssssssssssssssssssssssssssssssssssssss Bro   :+1:

**Comment by corneal64** [comment]
That's awesome !👏
