### ISSUE TITLE
Raspberry Pi Zero

### ISSUE THREAD

**Issue by mocallins** [corneal64/Realtek-USB-Wireless-Adapter-Drivers#9]
Should this driver be ok on a Raspberry Pi Zero (not W)) ?

**Comment by ristomatti** [comment]
@mocallins You might have an easier ride with https://github.com/kelebek333/rtl8188fu/tree/arm. Both seem to be based on the same driver code but kelebek333's one has a branch and instructions for building on ARM.

**Comment by corneal64** [comment]
Try this, ARM support added.

https://github.com/corneal64/Realtek-USB-Wireless-Adapter-Drivers/tree/ARM-driver
